Pages/GamesCatalog/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyWebApp.Data;
using MyWebApp.Data.Identity;

namespace MyWebApp.Pages.GamesCatalog
{
    [Authorize(Roles = "Admin, Editor")]
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public CreateModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Games Games { get; set; } = default!;

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Games.Add(Games);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/GamesCatalog/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyWebApp.Data;
using MyWebApp.Data.Identity;

namespace MyWebApp.Pages.GamesCatalog
{
    [Authorize(Roles = "Admin, Editor")]
    public class DeleteModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public DeleteModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Games Games { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var games = await _context.Games.FirstOrDefaultAsync(m => m.Id == id);

            if (games == null)
            {
                return NotFound();
            }
            else
            {
                Games = games;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var games = await _context.Games.FindAsync(id);
            if (games != null)
            {
                Games = games;
                _context.Games.Remove(Games);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/GamesCatalog/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyWebApp.Data;
using MyWebApp.Data.Identity;

namespace MyWebApp.Pages.GamesCatalog
{
    [Authorize(Roles = "Admin, Editor, Clinet")]
    public class DetailsModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public DetailsModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public Games Games { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var games = await _context.Games.FirstOrDefaultAsync(m => m.Id == id);
            if (games == null)
            {
                return NotFound();
            }
            else
            {
                Games = games;
            }
            return Page();
        }
    }
}

Pages/GamesCatalog/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyWebApp.Data;
using MyWebApp.Data.Identity;

namespace MyWebApp.Pages.GamesCatalog
{
    [Authorize(Roles = "Admin, Editor")]
    public class EditModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public EditModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Games Games { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var games =  await _context.Games.FirstOrDefaultAsync(m => m.Id == id);
            if (games == null)
            {
                return NotFound();
            }
            Games = games;
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Games).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!GamesExists(Games.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool GamesExists(int id)
        {
            return _context.Games.Any(e => e.Id == id);
        }
    }
}

Pages/GamesCatalog/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyWebApp.Data;
using MyWebApp.Data.Identity;
using System.Threading.Tasks;

namespace MyWebApp.Pages.GamesCatalog
{
    [Authorize(Roles = "Admin, Editor, Client")]
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public IndexModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<Games> Games { get; set; } = default!;

        public async Task OnGetAsync()
        {
            Games = await _context.Games.ToListAsync();
        }

        public async Task<IActionResult> OnPostAddToCartAsync(int gameId)
        {
            var game = await _context.Games.FindAsync(gameId);

            if (game != null && game.QuantityAvailable > 0)
            {

                game.QuantityAvailable--;

                if (game.QuantityAvailable == 0) // Если QuantityAvailable стало 0, установите Avalible в false
                {
                    game.Avalible = false;
                }


                await _context.SaveChangesAsync();

                Games = await _context.Games.ToListAsync();

                return Page();
            }
            else
            {
                return RedirectToPage("/Error");
            }
        }
    }
}

Pages/Users/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MyWebApp.Data.Identity;

namespace MyWebApp.Pages.Users
{
    [Authorize(Roles = "Admin")]
    public class DeleteModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public DeleteModel(ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public AspUserShow AspUserShow { get; set; } = default!;

        [BindProperty]
        public ApplicationIdentityUser ApplicationUser { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FirstOrDefaultAsync(m => m.Id == id);

            if (user == null)
            {
                return NotFound();
            }
            else
            {
                ApplicationUser = user;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                ApplicationUser = user;
                _context.Users.Remove(ApplicationUser);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }

    }
}

Pages/Users/Edit.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Identity;
using MyWebApp.Data.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace MyWebApp.Pages.Users
{
    [Authorize(Roles = "Admin")]
    public class EditModel : PageModel
    {
        private readonly UserManager<ApplicationIdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public EditModel(UserManager<ApplicationIdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        [BindProperty]
        public string UserName { get; set; }

        [BindProperty]
        public string Email { get; set; }

        [BindProperty]
        public string Id { get; set; }

        [BindProperty]
        public List<string> SelectedRoles { get; set; }

        public SelectList RolesList { get; set; }

        [BindProperty]
        public string RoleName { get; set; }

        public async Task OnGetAsync(string id)
        {
            var user = await _userManager.FindByIdAsync(id.ToString());

            if (user != null)
            {
                UserName = user.UserName;
                Email = user.Email;
                Id = user.Id;

                var roles = await _roleManager.Roles.ToListAsync();
                RolesList = new SelectList(roles, nameof(IdentityRole.Name), nameof(IdentityRole.Name));

                var userRoles = await _userManager.GetRolesAsync(user);
                SelectedRoles = userRoles.ToList();

                RoleName = userRoles.FirstOrDefault();
            }

        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var user = await _userManager.FindByIdAsync(Id.ToString());

            if (user != null)
            {
                user.UserName = UserName;
                user.Email = Email;

                var result = await _userManager.UpdateAsync(user);

                if (result.Succeeded)
                {
                    var userRoles = await _userManager.GetRolesAsync(user);
                    await _userManager.RemoveFromRolesAsync(user, userRoles);
                    await _userManager.AddToRolesAsync(user, SelectedRoles);

                    RoleName = SelectedRoles.FirstOrDefault();

                    return RedirectToPage("./Index");
                }
            }

            return Page();
        }
    }
}

Pages/GamesCatalog/Create.cshtml
@page
@model MyWebApp.Pages.GamesCatalog.CreateModel

@{
    ViewData["Title"] = "Добавить новую";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Добавить новую</h1>

<h4>Игры</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Games.NameOfTheGame" class="control-label"></label>
                <input asp-for="Games.NameOfTheGame" class="form-control" />
                <span asp-validation-for="Games.NameOfTheGame" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Games.Price" class="control-label"></label>
                <input asp-for="Games.Price" class="form-control" />
                <span asp-validation-for="Games.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Games.QuantityAvailable" class="control-label"></label>
                <input asp-for="Games.QuantityAvailable" class="form-control" />
                <span asp-validation-for="Games.QuantityAvailable" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Games.Avalible" /> @Html.DisplayNameFor(model => model.Games.Avalible)
                </label>
            </div>
            <div class="form-group">
                <input id="color-button" type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a id="color-link" asp-page="Index">Вернуться</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/GamesCatalog/Delete.cshtml
@page
@model MyWebApp.Pages.GamesCatalog.DeleteModel

@{
    ViewData["Title"] = "Удалить";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Удалить</h1>

<h3>Вы уверены, что хотите удалить это?</h3>
<div>
    <h4>Игры</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Games.NameOfTheGame)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Games.NameOfTheGame)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Games.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Games.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Games.QuantityAvailable)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Games.QuantityAvailable)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Games.Avalible)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Games.Avalible)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Games.Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a id="color-link" asp-page="./Index">Вернуться</a>
    </form>
</div>

Pages/GamesCatalog/Details.cshtml
@page
@model MyWebApp.Pages.GamesCatalog.DetailsModel

@{
    ViewData["Title"] = "Детали";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Детали</h1>

<div>
    <h4>Игры</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Games.NameOfTheGame)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Games.NameOfTheGame)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Games.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Games.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Games.QuantityAvailable)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Games.QuantityAvailable)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Games.Avalible)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Games.Avalible)
        </dd>
    </dl>
</div>
<div>
    <a id="color-link" asp-page="./Edit" asp-route-id="@Model.Games.Id">Редактировать</a> |
    <a id="color-link" asp-page="./Index">Вернуться</a>
</div>

Pages/GamesCatalog/Edit.cshtml
@page
@model MyWebApp.Pages.GamesCatalog.EditModel

@{
    ViewData["Title"] = "Редактирование";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Редактирование</h1>

<h4>Игры</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Games.Id" />
            <div class="form-group">
                <label asp-for="Games.NameOfTheGame" class="control-label"></label>
                <input asp-for="Games.NameOfTheGame" class="form-control" />
                <span asp-validation-for="Games.NameOfTheGame" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Games.Price" class="control-label"></label>
                <input asp-for="Games.Price" class="form-control" type="number" step="0.01" />
                <span asp-validation-for="Games.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Games.QuantityAvailable" class="control-label"></label>
                <input asp-for="Games.QuantityAvailable" class="form-control" />
                <span asp-validation-for="Games.QuantityAvailable" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Games.Avalible" /> @Html.DisplayNameFor(model => model.Games.Avalible)
                </label>
            </div>
            <div class="form-group">
                <input id="color-button" type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a id="color-link" asp-page="Index">Вернуться</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/GamesCatalog/Index.cshtml
@page
@model MyWebApp.Pages.GamesCatalog.IndexModel
@using Microsoft.AspNetCore.Identity
@using MyWebApp.Data.Identity
@inject SignInManager<ApplicationIdentityUser> SignInManager

@{
    ViewData["Title"] = @"Каталог игр";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Каталог игр</h1>

@if (SignInManager.IsSignedIn(User))
{
    @if (User.IsInRole("Admin") || User.IsInRole("Editor"))
    {
        <p>
            <a id="color-link" asp-page="Create">Добавить новую игру</a>
        </p>
    }
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Games[0].NameOfTheGame)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Games[0].Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Games[0].QuantityAvailable)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Games[0].Avalible)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Games)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.NameOfTheGame)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.QuantityAvailable)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Avalible)
                    </td>
                    @if (User.IsInRole("Admin") || User.IsInRole("Editor"))
                    {
                        <td>
                            <a id="color-link" asp-page="./Edit" asp-route-id="@item.Id">Отредактировать</a> |
                            <a id="color-link" asp-page="./Details" asp-route-id="@item.Id">Детали</a> |
                            <a id="color-link" asp-page="./Delete" asp-route-id="@item.Id">Удалить</a>
                        </td>
                    }

                    @if (User.IsInRole("Client") && item.Avalible)
                    {
                        <td>
                            <form method="post" asp-page-handler="AddToCart">
                                <input type="hidden" name="gameId" value="@item.Id" />
                                <button type="submit">Купить</button>
                            </form>
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <span>NOT Logged In</span>
}